### ISSUE TITLE
youtube support

### ISSUE THREAD

**Issue by pietrondo** [i8beef/node-red-contrib-castv2#1]
Is possible to use with youtube video ?
thx

**Comment by i8beef** [comment]
Sorry, didn't see this. But I think the answer is no. YouTube isn't a DefaultMediaReceiver activity, it requires its own receiver implementation like this: https://github.com/irfanhabib/youtube-castv2-client. This approach doesn't really lend itself to modularity.... YouTube support is probably a valid support, but then so would Netflix support, Spotify support, and any number of other "custom receivers", which is a bit out of scope here.

However, someone could conceivably take this implementation and make a SPECIFIC node just for YouTube support / control using that other library. Heck, if it was implemented well, I'd consider PRs adding such a secondary node to this module... and any of those others too if someone put in the leg work.

**Comment by i8beef** [comment]
I am adding YouTube support in 3.0.0 which should be published shortly.

**Comment by i8beef** [comment]
Resolved in 3.0.0, please try it out and let me know if you have issues!
