### ISSUE TITLE
Unable to install - EINVALIDTAGNAME

### ISSUE THREAD

**Issue by hathawaj** [i8beef/node-red-contrib-castv2#101]
Hello, I'm stuck right at the start as the installation, both from within node red and the command line, fails for me. It seems to be complaining about the release tag. Full error  log below from the command line install. Is there a different method to install by downloading direct from github perhaps?  Many thanks, John.

john@raspberrypi:~/.node-red $ npm install node-red-contrib-castv2
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name ""~"4.3.0" of package "node-red-contrib-castv2@"~"4.3.0": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/john/.npm/_logs/2023-12-18T23_07_34_748Z-debug-0.log
john@raspberrypi:~/.node-red $ cat /home/john/.npm/_logs/2023-12-18T23_07_34_748Z-debug-0.log
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@8.19.4
2 info using node@v16.20.2
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 5ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 4ms
8 timing config:load:env Completed in 2ms
9 timing config:load:file:/home/john/.node-red/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/home/john/.npmrc Completed in 2ms
12 timing config:load:user Completed in 4ms
13 timing config:load:file:/usr/etc/npmrc Completed in 3ms
14 timing config:load:global Completed in 4ms
15 timing config:load:validate Completed in 2ms
16 timing config:load:credentials Completed in 3ms
17 timing config:load:setEnvs Completed in 4ms
18 timing config:load Completed in 36ms
19 timing npm:load:configload Completed in 36ms
20 timing npm:load:mkdirpcache Completed in 3ms
21 timing npm:load:mkdirplogs Completed in 1ms
22 verbose title npm install node-red-contrib-castv2
23 verbose argv "install" "node-red-contrib-castv2"
24 timing npm:load:setTitle Completed in 4ms
25 timing config:load:flatten Completed in 8ms
26 timing npm:load:display Completed in 14ms
27 verbose logfile logs-max:10 dir:/home/john/.npm/_logs
28 verbose logfile /home/john/.npm/_logs/2023-12-18T23_07_34_748Z-debug-0.log
29 timing npm:load:logFile Completed in 15ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 77ms
33 timing arborist:ctor Completed in 2ms
34 silly logfile start cleaning logs, removing 1 files
35 silly logfile done cleaning log files
36 timing idealTree:init Completed in 1277ms
37 timing idealTree:userRequests Completed in 17ms
38 silly idealTree buildDeps
39 timing idealTree Completed in 1305ms
40 timing command:install Completed in 1344ms
41 verbose stack Error: Invalid tag name ""~"4.3.0" of package "node-red-contrib-castv2@"~"4.3.0": Tags may not have any characters that encodeURIComponent encodes.
41 verbose stack     at invalidTagName (/usr/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:98:15)
41 verbose stack     at fromRegistry (/usr/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:397:13)
41 verbose stack     at Function.resolve (/usr/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:85:12)
41 verbose stack     at Arborist.[nodeFromEdge] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1060:22)
41 verbose stack     at Arborist.[buildDepStep] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:930:36)
41 verbose stack     at Arborist.[buildDeps] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:778:31)
41 verbose stack     at Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:211:29)
41 verbose stack     at async Promise.all (index 1)
41 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:154:5)
41 verbose stack     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:145:5)
42 verbose cwd /home/john/.node-red
43 verbose Linux 5.10.103-v7l+
44 verbose node v16.20.2
45 verbose npm  v8.19.4
46 error code EINVALIDTAGNAME
47 error Invalid tag name ""~"4.3.0" of package "node-red-contrib-castv2@"~"4.3.0": Tags may not have any characters that encodeURIComponent encodes.
48 verbose exit 1
49 timing npm Completed in 1718ms
50 verbose unfinished npm timer reify 1702940855111
51 verbose unfinished npm timer reify:loadTrees 1702940855140
52 verbose unfinished npm timer idealTree:buildDeps 1702940856439
53 verbose unfinished npm timer idealTree:#root 1702940856441
54 verbose code 1
55 error A complete log of this run can be found in:

**Comment by i8beef** [comment]
NPM apparently changed something about their dependency chain stuff again. Try running with `--legacy-peer-deps` and it should pass.

**Comment by hathawaj** [comment]
That seems to have done the trick. Many thanks for the prompt response.

John.
