### ISSUE TITLE
Can I cast to Kodi?

### ISSUE THREAD

**Issue by Barabba11** [i8beef/node-red-contrib-castv2#104]
Hi, I'm trying to work with this module but since now I haven't success, I need it working on an Android TV (not Google OS), so forst I simply tries to connect to it with its IP+ port 8009 (network is 100% working) and have no connection, then I installed on TV the cast server apk, opened it and didn't work, so I've tried with Kodi with all services enabled, nothing.
So I moved on PC, I run Kodi here and I've tried to connect to all Kodi's opened TCP ports, but always I got error connection. I'm using Kodi because I suppose it supports all possibile protocols, is it true? Then, how can I cast to it?

May you please explain me how the module is supposing to work? Is it necessary the receiver has the 8009 opened? (I mean, a specific protocol used by that port)
Thank you for supporting!

**Comment by i8beef** [comment]
It sounds like you are missing how Google Cast works in general here... Kodi isn't a cast target that I know of, its a cast SENDER, just like this node. Im assuming you'd want to cast to your Android TV, but it sounds like you are using a Chinese brand box or something? If so I have no idea what they do or do not support in regards to Google Cast.

As a first step, you'll want to figure out how to get something like your phone or PC to cast to your target... if you can't get that to work, this node isn't going to work either, and at least you stand a better chance finding documentation for whatever device you are trying to cast to that way. It SOUNDS like whatever that Android TV box is that you have isn't exposing a cast target, so you'll have to figure out how to get it to do that first.

**Comment by i8beef** [comment]
Closing as stale, reopen if you need more answers!
