### ISSUE TITLE
TypeError: util.promisify is not a function

### ISSUE THREAD

**Issue by SuperJuke** [i8beef/node-red-contrib-castv2#15]
I'm getting the following error in Node-Red:

"TypeError: util.promisify is not a function"

Was on node v7.4.0, upgraded to v8.17.0 and v10.2.0, still the same error.

Can you please help?

**Comment by i8beef** [comment]
I bet you'll find you're still running on 7 somehow. Promisify wasnt a thing until 8.0. node red doesn't even support anything older than 10.0 lts at this point, so I think you're going to have to figure out what's messed up with your node install. I'm not a node expert at all, so you might get better help here from the node red forums...

**Comment by SuperJuke** [comment]
I'm running NVM which can switch between  versions of Node. Pretty sure it is on v10 right now. My node-red however is version 0.16. That might be the issue. Been holding back the upgrade of node-red because version 1 breaks the CSS from the older versions. Guess I will have to figure this out.

**Comment by i8beef** [comment]
If `util.promisify` isn't defined, then I'm pretty sure you must be running on a node before 8.x... I'm not sure how node-red would be specifying a different version. Remember, if you're running under docker you are running the node version in the container, not the one on the host system.

You might also read through this on their faq: https://nodered.org/docs/faq/node-versions#using-nvm

**Comment by SuperJuke** [comment]
Got it working. Was running an old Node-red in Docker. Replaced it with the latest docker image for Node-Red, v1.0.3. Thanks.
