### ISSUE TITLE
type:CLOSE not working anymore

### ISSUE THREAD

**Issue by hgghyxo** [i8beef/node-red-contrib-castv2#24]
Hi

node-red-contrib-castv2 version: 3.1.0

on payload.type: CLOSE got the following error: 

"TypeError: self.stop is not a function"
 
Device used: Google Home mini

**Comment by i8beef** [comment]
What application is running when you get this issue? Is it a normal DefaultMediaReceiver media cast, or are you closing YouTube, Spotify, etc.?

**Comment by hgghyxo** [comment]
Spotify

**Comment by i8beef** [comment]
Yeah, I see it. Ill get another fix out this afternoon. The YouTube one is gonna have the same issue.

**Comment by i8beef** [comment]
3.1.1 should be available shortly, try that.

**Comment by hgghyxo** [comment]
sure, thank you. Will test it out !
