### ISSUE TITLE
Update metadata without interrupting stream.

### ISSUE THREAD

**Issue by strelniece** [i8beef/node-red-contrib-castv2#25]
Hi,

I cast a livestream (radio channel) to my chromecast audio and update the metadata whenever there is a new program, the stream itsself contains no metadata, unfortunatly... 

Since the last update, it is defenetly doable, thank you! but there is a very short pause when the node updates.

Is it possible to update metadata only, without interrupting the audio stream? I've tried a couple of things, but so far no luck...

**Comment by i8beef** [comment]
I don't follow what you're trying to do. With the new model, the Cast connection is maintained permanently, and the Cast device will send its updates in a push manner (i.e., you shouldn't be polling for information). Am I misunderstanding what you're doing?

**Comment by strelniece** [comment]
Hi,
Sorry, not always easy to be clear  in your native language, and even less in another...

I live stream my favourite radio station, their stream is audio only, no metada at all. 

So the metadata has to be added by it self and updated every time a new program starts. 

So far I haven't found a way to update the metadata without also including the live-stream url so the stream will make a short pause, it is very short, less than a second, but rather annoying. 

So is it possible to update only the metadata, without affecting the live stream? 

I hope I managed to explain better now. 

Also, a big thank you for implementing the permanent connection, before that it was defenetly not possible to at all to do this...

**Comment by i8beef** [comment]
Got it. No this isn't possible that I'm aware of. Every MEDIA command will start a new cast load. I am not aware of any way to load additional metadata after media has loaded.

**Comment by strelniece** [comment]
I was afraid that was the case...

I was digging through Googles documentation and if I understand it correctly that there is i new SDK, CAF, where it's possible to update metadata only.

Any chanche you will update the node to CAF?

**Comment by i8beef** [comment]
Nope. The actual cast implementation here is all handled under the hood by a third party library (castv2, thus the node name). CAF is a completely different animal which, to my knowledge, no one has written a node library to support yet.

**Comment by i8beef** [comment]
Closing as there's not a way to enable this functionality.
