### ISSUE TITLE
TTS Text length constraint?

### ISSUE THREAD

**Issue by Andoramb** [i8beef/node-red-contrib-castv2#26]
Hi!
I wonder if there is a limitation for the input text for tts?
I'm generating notification text based on a couple inputs from a database. Sometimes this generated text is longer than 200 characters, and it returns: 
"RangeError: text length (204) should be less than 200 characters"

Is there a possibility to bypass that? I'm not talking about a novel here 😄 

Thanks for the node!

**Comment by i8beef** [comment]
Sorry, that looks to be a constraint of the Google TTS library, not something I can bypass.

**Comment by i8beef** [comment]
Closing as there's nothing we can do here.

**Comment by Andoramb** [comment]
Oh yes, sorry, I forgot to close it. Thanks!
