### ISSUE TITLE
Add Suport to inform msg.host

### ISSUE THREAD

**Issue by soloam** [i8beef/node-red-contrib-castv2#28]
Hello, I know that probably this one is hard (because of the way the node is designed), but it would be nice if we were able to call a cast dynamic informing msg.host (for example) in the message. That would avoid having a node for all the casts, we would be able to inform the ip in the message and call the node dynamic. Example

```json
{
   "payload":{"type":"PLAY"},
   "ip":"192.168.1.20"
}
```

Thank You

**Comment by i8beef** [comment]
Sorry, but the new model expressly contradicts this. We give up run-time targeting in favor of always-live connection management.
