### ISSUE TITLE
Media array don't load 

### ISSUE THREAD

**Issue by Dizzybacon** [i8beef/node-red-contrib-castv2#3]
The format for a list of media urls doesn't load.

`{
  host: "1.1.1.1",
  payload: {
    type: "MEDIA",
    media: [
      { url: "http://test.com/media.mp3", ... },
      { url: "http://test.com/someOtherMedia.mp3", ... },
      ...
    ]
  }
}`

Returns a format error.

**Comment by i8beef** [comment]
Yeah this is untested. What is throwing a format error? I don't think I throw anything with the word "format" in it.

**Comment by i8beef** [comment]
I'm pushing 1.1.6 which you can try. It fixes a different issue, but might actually resolve yours as well.

**Comment by Dizzybacon** [comment]
Tried upgrading to 1.1.6, the error message has disappeared, but no media plays still.

**Comment by jparthum** [comment]
Also on 1.1.6 but getting an error.
Sending this...
`payload`:
```
{
   "media":[
       {
           "url":"https://MYDOMAIN:8920/Audio/6274/universal?UserId=208d3349ad084fa8bc6b4539214a8d41&MaxStreamingBitrate=140000000&Container=opus,mp3,aac,m4a,flac,webma,webm,wav,ogg,aac,mp3,mpa,wav,wma,mp2,ogg,oga,webma,ape,opus,flac,m4a&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&MaxSampleRate=48000&PlaySessionId=1496213367201",
           "contentType":"audio/mp3",
           "streamType":"BUFFERED",
           "title":"We Rock",
           "image":"https://MYDOMAIN:8920/emby/Items/6274/Images/Primary/0"
       },
       {
           "url":"https://MYDOMAIN:8920/Audio/6952/universal?UserId=208d3349ad084fa8bc6b4539214a8d41&MaxStreamingBitrate=140000000&Container=opus,mp3,aac,m4a,flac,webma,webm,wav,ogg,aac,mp3,mpa,wav,wma,mp2,ogg,oga,webma,ape,opus,flac,m4a&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&MaxSampleRate=48000&PlaySessionId=1496213367201",
           "contentType":"audio/mp3",
           "streamType":"BUFFERED",
           "title":"Im Rhythmus Bleiben",
           "image":"https://MYDOMAIN:8920/emby/Items/6952/Images/Primary/0"
       },
       {
           "url":"https://MYDOMAIN:8920/Audio/12974/universal?UserId=208d3349ad084fa8bc6b4539214a8d41&MaxStreamingBitrate=140000000&Container=opus,mp3,aac,m4a,flac,webma,webm,wav,ogg,aac,mp3,mpa,wav,wma,mp2,ogg,oga,webma,ape,opus,flac,m4a&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&MaxSampleRate=48000&PlaySessionId=1496213367201",
           "contentType":"audio/mp3",
           "streamType":"BUFFERED",
           "title":"Stairway To Heaven",
           "image":"https://MYDOMAIN:8920/emby/Items/12974/Images/Primary/0"
       }
   ],
   "type":"MEDIA"
}
```

...gives me:
`Error: Invalid request: INVALID_PARAMS`

Is my syntax correct?

**Comment by i8beef** [comment]
Try 1.1.7 which should be published here soon

**Comment by jparthum** [comment]
Confirmed: Arrays working great on 1.1.7.

Thanks for fixing so quickly.

**Comment by i8beef** [comment]
Wow worked first try huh? I wonder what I did wrong that you didn't find yet, lol. Feel free to reopen if anything is missing.

**Comment by jparthum** [comment]
Yep, worked beautifully on the first try... [metadata](https://developers.google.com/cast/docs/reference/messages#GenericMediaMetadata) and all!
I was pleasantly surprised since I wasn't sure my own syntax was correct.

Thanks again for the great work.
