### ISSUE TITLE
Integration of Google Cloud: Text-to-Speech

### ISSUE THREAD

**Issue by Anjerlaan** [i8beef/node-red-contrib-castv2#32]
Hi man,

I was wondering if the Google Cloud **Text-to-Speech** API could be intergrated in "node-red-contrib-castv2"?
https://cloud.google.com/text-to-speech

This sounds much more natural than the default TTS
Try it yourself, if not already done ;-)

![afbeelding](https://user-images.githubusercontent.com/18295963/93127166-b3977e80-f6cd-11ea-9415-d95e3509b0c7.png)

**Comment by i8beef** [comment]
Not likely as that would require users to setup their own API keys. By using the translate endpoint it can all be done anonymously.

**Comment by i8beef** [comment]
Closed as out of scope.
