### ISSUE TITLE
Stripped out variables

### ISSUE THREAD

**Issue by ReggieP123** [i8beef/node-red-contrib-castv2#39]
Hi,

I wonder if it's possible that the node can be less destructive to other variables that I'd like to passthrough.

I understand that it uses msg.payload and it creates msg.platform...probably amoungst others. But, for instance, if I've created a variable called msg.payload2 in a node before castv2, it gets stripped out from the message. Is there anyway these variables can be kept and just passed through?

Reggie

**Comment by i8beef** [comment]
Sorry, but that doesn't fit with the usage of this node. Though it can appear that you are getting a request/response pattern here, the actual node architecture is built around an async path for messages. Think of it more like a node that has distinct IN / OUT nodes, just combined into one for simplicity of connection management and such. The original msg has no meaning after being sent, and the outgoing msg has no inherent connection to the incoming one.

**Comment by ReggieP123** [comment]
No problem. Thank you for your detailed reply. I'll use a flow variable to acheive what I'm looking to do.

Reggie
