### ISSUE TITLE
Casting image

### ISSUE THREAD

**Issue by nygma2004** [i8beef/node-red-contrib-castv2#4]
I was trying to cast a single image (screenshot from front IP camera) and I wanted to cast that to Google Home Hub:
{
  host: "192.168.1.185",
  payload: {
    type: "MEDIA",
    media: {
      url: "https://kep.cdn.indexvas.hu/1/0/3028/30282/302824/30282419_2324873_d227edf89f4452c396e50d8b9166debf_wm.jpg",
      title: "Front Gate", // optional unless desired
    }
  }
}
Actually this URL is a generic picture form the new. I hear the ping sound, and the chromecast icon but nothing gets displayed. Do you know how this can work? I could not find any reference if this is a different media type or something.

**Comment by nygma2004** [comment]
I am sorry, I was passing this to msg.payload and not msg. It works :)

**Comment by i8beef** [comment]
Glad to hear you figured it out!
