### ISSUE TITLE
Change voice

### ISSUE THREAD

**Issue by Actesis** [i8beef/node-red-contrib-castv2#40]
Along with language, Google allows multiple voice selections.  Is this possible to be done with castv2?

**Comment by i8beef** [comment]
No, not possible at this time. Google has changed their TTS implementation again which has broken use of the API proper for free use, so right now I'm not even using that, Im just generating the unprotected URL which to my knowledge doesn't support that.

If you can find a way around that, Im open to PRs though.

**Comment by Actesis** [comment]
Yeah, I saw they changed the API again.  ugh.  I use Hubitat as well, and they have the ability to change voice.  I'm not sure how they're doing it though as they don't expose code for built-in apps.  :-/

**Comment by i8beef** [comment]
Its possible they pay for an actual Google Translate API key which allows them to use the full set of features. Those of us sponging off Google with these reverse engineered non-kosher uses of their public APIs are a little limited to what we can do 😄

**Comment by i8beef** [comment]
Gonna close this for now. If we ever get a full access TTS API that won't require API key setup by users, Ill definitely look at exposing more of these options, but everything I see so far says that there's no equivalent here for the public endpoint we are using...
