### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by bilalasd** [i8beef/node-red-contrib-castv2#47]
Hi,

Maybe I'm doing something wrong but, changing the "speed" settings when using tts isn't doing anything.

Thanks,

**Comment by i8beef** [comment]
Yeah, Google changed things a while back and there's a temporary hack in place to keep TTS working. Speed is not currently supported until the TTS APIs can be used again instead of the google translate hack.

**Comment by i8beef** [comment]
Actually, it looks like someone might have figured out how to pass a speed again, Ill push a new version and see if it works.

**Comment by i8beef** [comment]
So it DOES work with the new version, but it seems the Google translate API behind it only supports a few values for the speed... I could only get 0.1, 0.2, and 0.3 to have any appreciable difference, and nothing above that (i.e., I can't make it talk faster, etc.). Best I can do for now.
