### ISSUE TITLE
Connecting > disconnected 

### ISSUE THREAD

**Issue by spanout** [i8beef/node-red-contrib-castv2#48]
Changed to this component when tts started failing on old cast node. The node is alternating between connecting and disconnected. The ip address is correct. What else can i check? I have checked it on a google home speaker and nest audio speaker and get the same result.

**Comment by i8beef** [comment]
Make sure the "target" field is empty in the connection settings if you aren't using mDNS discovery. It will attempt to use that preferentially if its there.

**Comment by spanout** [comment]
That fixed it. Thanks
