### ISSUE TITLE
Does the queue commands work with an image array?

### ISSUE THREAD

**Issue by bbigras** [i8beef/node-red-contrib-castv2#55]
I'm trying to do something like:

```json
msg.payload = {"app":"DefaultMediaReceiver","type":"MEDIA","media":[{"url":"https://www.pinclipart.com/picdir/big/73-730178_derpy-batman-derp-batman-png-clipart.png"},{"url":"https://i.imgur.com/n4EHAPj.png"}]}
```

The first image works but `QUEUE_PREV` and `QUEUE_NEXT` don't seem to work.

**Comment by i8beef** [comment]
Doesn't look like it if this answer is to be trusted: https://stackoverflow.com/questions/30915484/queue-mutiliples-image-on-chromecast-with-gckmediaqueueitem

**Comment by bbigras** [comment]
Any idea if this answer could help? https://stackoverflow.com/a/36416022

**Comment by i8beef** [comment]
Nope. This is a function of the google DefaultMediaReceiver to support or not for specific media types. It just doesn't look like they support image queues. If you find other information to contradict that I'm happy to look again. There's not a lot of options here though, there's only a subset of commands to work with, and they are kinda either gonna work or not.

**Comment by i8beef** [comment]
Closing as not supported upstream.
