### ISSUE TITLE
Add broadcast option TTS?

### ISSUE THREAD

**Issue by kkoenig77** [i8beef/node-red-contrib-castv2#6]
Hey, This works great and thanks for you work on it.

It would be an awesome addition if the TTS option was configured for broadcast instead of starting a new stream. This way it would not stop media that is already playing. 

similar to- https://github.com/greghesp/assistant-relay

**Comment by i8beef** [comment]
Cool idea, and in fact I "simulate" this by just casting to all my homes at once... but its not as nice of an effect as an actual broadcast. The ask here unfortunately isn't trivial, and might be better handled by a dedicated Google Assistant API node of some sort. This is really meant to deal only with the Cast APIs so it can target more than just Google Homes.

**Comment by melvinraju** [comment]
I am also looking for this functionality to play a TTS over a stream of my doorbell cam. Currently have to play the TTS first and then show the cam which isnt a great user experience.

**Comment by i8beef** [comment]
As this node is specifically supporting the Google Cast protocol, Im going to say this isn't going to happen. The ask here is actually for an implementation of the Google Assistant SDK, which is out of scope... they are just two different animals.

If someone wanted to create a node for exposing that, they might look at the [google-assistant NPM package](https://www.npmjs.com/package/google-assistant), and could probably use the [assistant-relay project](https://github.com/greghesp/assistant-relay) as a good example of how to integrate.
