### ISSUE TITLE
Documentation issue GET_CAST_STATUS

### ISSUE THREAD

**Issue by qib1400** [i8beef/node-red-contrib-castv2#60]
The correct command to get the status of the device is GET_STATUS (line 380 of the castv2-sender.js) not GET_CAST_STATUS as described in the documentation

**Comment by i8beef** [comment]
Both are valid. GET_CAST_STATUS gets the CAST DEVICE status (Always available) while GET_STATUS gets the current active media status. If nothing is currently playing, or the current running app doesn't support a "status" report, GET_STATUS won't do anything.

You aren't the first to be confused by this, and I've kicked the idea of renaming these, but I haven't wanted to break anyone using the existing API yet. In a perfect world, I would have used "GET_STATUS" for the device status, and then something like "GET_APP_STATUS" for the other one.

**Comment by i8beef** [comment]
Closing as stale
