### ISSUE TITLE
Queue multiple videos

### ISSUE THREAD

**Issue by Varguit** [i8beef/node-red-contrib-castv2#65]
Hi all.
First of all, thanks @i8beef for this great node, I'm using it every day on my home automations.
My question is related to the possibility of sending multiple video id's to my chromecast, I've tried several ways without success.

This is sending 2 video id's as an example, but only the first one is playing, I'd like to queue a list of videos if possible.

```
msg.payload = {
                app: "YouTube",
                type: "MEDIA",
                videoId: [
                    "EWMLL5bxqJk",
                    "PnMTHquErKk"
                ]
            }

return msg;
```
Thanks.

**Comment by i8beef** [comment]
The YouTube controller does not support multiple videos. Im actually surprised that even the first one plays.

**Comment by Varguit** [comment]
Thanks for your reply, actually you are right, not even the first one plays with the code I've posted.
