### ISSUE TITLE
Error: Not connected

### ISSUE THREAD

**Issue by Gjaltz** [i8beef/node-red-contrib-castv2#67]
node-red-contrib-castv2 is Connecting / disconnecting the whole time.

**Comment by i8beef** [comment]
That means its stuck in a reconnect loop. It can't reach the target you have specified.

**Comment by Gjaltz** [comment]
After executing tts payload now in error status. Streams are working fine.

**Comment by i8beef** [comment]
If you are seeing issues with TTS specifically, then you need to read through the other open issue. Are you seeing general connect/disconnect looping, or are you seeing an error when sending a TTS payload specifically?

**Comment by i8beef** [comment]
Closing as stale.
