### ISSUE TITLE
Malformed media command

### ISSUE THREAD

**Issue by hav0ck** [i8beef/node-red-contrib-castv2#7]
I am trying to get Pause, Stop, and Play working but when I trigger these I get "Malformed media command"
My JSON looks like:
```
{
    "type": "PAUSE"
}
```
I am able to get Mute and Unmute to work using the same JASON format as above.

**Comment by i8beef** [comment]
Ah I think I see the problem. Let me take a look this evening.

**Comment by i8beef** [comment]
1.1.5 Should be out in 30 minutes or so. Try that out and see if its better for you.

**Comment by hav0ck** [comment]
Limited testing but Play, Pause, and Stop appear to be working as expected

**Comment by i8beef** [comment]
Glad to hear it! I fixed the notifications on Github so if you have any other issues just ask, and Ill try and get back to you quicker next time.

**Comment by dezral** [comment]
I can't get it to pause any media like Youtube.. the player just exits.. and if i send the command

{"type":"PAUSE"} as an JSON parsed it comes with an error.. no error as a string.. but still exits.

im trying to have a funktion that can pause what ever is playing on the chromecast from a switch.
