### ISSUE TITLE
Cast dashboard (URL)

### ISSUE THREAD

**Issue by dannymertens** [i8beef/node-red-contrib-castv2#72]
Hi,

Is it possible to cast a URL for a dashboard like for instance Home assistant Lovelace view, so no video, audio just a normal webpage URL

Example: http://192.168.1.20:8123/dash-woonkamer-hub/home

Thanks in advance!

**Comment by i8beef** [comment]
Yes and no. You can use a Chromecast app called "DashCast" to do this by sending the node a message like this

```
{
    payload: { 
        app: "DashCast",
        type: "LOAD",
        url: "http://192.168.1.20:8123/dash-woonkamer-hub/home",
        force: true
    }
}
```

I played with this for a time and ultimately didn't move forward with it though for some reason I can't remember. It "worked" but not well, and as I recall the Google Cast devices didn't seem to have enough power to really deal with anything too complicated.

**Comment by i8beef** [comment]
Closing as answered.
