### ISSUE TITLE
No PAUZE event

### ISSUE THREAD

**Issue by JGoor** [i8beef/node-red-contrib-castv2#74]
Hi,

For my ChromecastV2, the PLAYING event is generated (Netflix).
When I pause Netflix, I used to get a BUFFERING event but not anymore.
YouTube however still provides me with  'PLAYING' and ' PAUSED' .

So something seems broken in the Netflix flow.

Eg. when I use YouTube and switch to Netflix, or I start a Netflix stream for the first time, the debugger shows the following output:

> 10/31/2021, 5:08:50 PMnode: c402913b466341b7msg.payload : Object
> { mediaSessionId: 1, playbackRate: 1, playerState: "IDLE", supportedMediaCommands: 4303, volume: object … }
> 10/31/2021, 5:08:50 PMnode: c402913b466341b7msg.payload : Object
> { mediaSessionId: 1, playbackRate: 1, playerState: "PLAYING", currentTime: null, supportedMediaCommands: 4303 … }
> 10/31/2021, 5:08:51 PMnode: c402913b466341b7msg.payload : Object
> { mediaSessionId: 1, playbackRate: 1, playerState: "PLAYING", currentTime: 0.001, supportedMediaCommands: 4303 … }
> 10/31/2021, 5:08:51 PMnode: c402913b466341b7msg.payload : Object
> { mediaSessionId: 1, playbackRate: 1, playerState: "BUFFERING", currentTime: 0.001, supportedMediaCommands: 4303 … }
> 10/31/2021, 5:08:52 PMnode: c402913b466341b7msg.payload : Object
> { mediaSessionId: 1, playbackRate: 1, playerState: "BUFFERING", currentTime: 0.001, supportedMediaCommands: 4303 … }
> 10/31/2021, 5:08:54 PMnode: c402913b466341b7msg.payload : Object
> { mediaSessionId: 1, playbackRate: 1, playerState: "PLAYING", currentTime: 0.143, supportedMediaCommands: 4303 … }
> 10/31/2021, 5:08:55 PMnode: c402913b466341b7
> msg.payload : Object
> { mediaSessionId: 1, playbackRate: 1, playerState: "PLAYING", currentTime: 1.235, supportedMediaCommands: 4303 … }

After that, it only shows 'PLAYING'  but never ' BUFFERING'  anymore.
Can you help out?

**Comment by i8beef** [comment]
As Netflix is not a directly supported application here, you are leaning on the "generic" application support. For COMMANDS it will accept and send through any "generic media commands" the app claims to support (supportedMediaCommands: 4303). For EVENTS, it's whatever the app publishes, and it sounds like the Netflix app has decided to change what it publishes.

There is nothing I can really do for that.

**Comment by i8beef** [comment]
Closing as this is a usage issue with distinct application, not a general cast issue.
