### ISSUE TITLE
Turn off the device?

### ISSUE THREAD

**Issue by tronoku** [i8beef/node-red-contrib-castv2#76]
Is there a way to turn off the device attached to the google chromecast?

Or do you recommend some way to sleep the cast? Like muting and set brightness to 0? maybe I should find a video that is completely black  and soundless

I will use a wall switch if necessary but I want to avoid that and use this nodered script

**Comment by i8beef** [comment]
I am not aware of a way to do that, no.

**Comment by i8beef** [comment]
Closing as the cast protocol doesn't allow specifically for direct control of connected devices, only with general media control.
