### ISSUE TITLE
[Enhancement] Multiroom option

### ISSUE THREAD

**Issue by hutje** [i8beef/node-red-contrib-castv2#78]
It would be so useful to be able to select the speakers you want to stream to simultaneously, without previously making a group.
Now when I stream to each individual speaker, it is not in sync and two separate sources.

**Comment by i8beef** [comment]
Unfortunately the cast protocol doesn't allow for multispeaker casts without setting up a group, and Google Home broadcasts are a different animal (not cast protocol).

**Comment by hgghyxo** [comment]
So if I understand correctly, even if I create a group previously, I'll not be able to use it as a cast output ? 

mDNS still not working for me, so I'm not able to confirm, if the groups is visible in the mDNS records or not, using the speakers individually by IP right now.

@i8beef Do you have any directions to start with this, maybe I can look into ? 

Thanks

**Comment by i8beef** [comment]
If you want to cast to a group, you have to setup that group, and you HAVE to use mDNS to talk to it. Google's cast protocol doesn't really give you another option. If you're having trouble with mDNS not showing you the cast groups, you have to troubleshoot that separately. Most likely things to check

1. If you're running node-red in Docker, you need to use another mdns repeater docker image to repeat the mDNS broadcasts onto the Docker container's network.
2. Some routers or firewalls might be setup to block mDNS / multicast broadcasts. Wireless access points sometimes have settings for this too. Obviously you'd have to investigate your own hardware settings for that.

**Comment by hgghyxo** [comment]
Thanks for the mDNS tips!
I'm running Nodered in a special k3s kubernetes envirnoment with docker runtime (truenas scale), at the moment, but this is temporary.
I'll fix this on my own, for sure, but it seems once I have mDNS sorted out I'll be able to use the pre-created groups.

Thanks again, I thought the implementation is not ready yet on your side, that's where I wanted to offer my help :)

**Comment by i8beef** [comment]
Closing as original issue is a non-cast related implementation that is out of scope.

**Comment by almostserious** [comment]
> Unfortunately the cast protocol doesn't allow for multispeaker casts without setting up a group, and Google Home broadcasts are a different animal (not cast protocol).

Is this still the case?
Right now in the Google Home app I can dynamically add and remove speakers to play the same musicstream.
This works with and without groups.
Is this feature not using the standard cast protocol?

**Comment by i8beef** [comment]
I am not aware of any such functionality in the cast v2 protocol, no. Google Home is a different animal, and not one that Google has really shared any useful APIs for still.
