### ISSUE TITLE
Feature Request: IP Tagging Outbound Message

### ISSUE THREAD

**Issue by ferris-smarthome** [i8beef/node-red-contrib-castv2#83]
If possible, I would like to request a feature where the outbound message from the node contains the IP Address of the device.  This would be useful in multiple device scenarios where post-processing would need to be done, based upon which device has responded.  The easiest example of this would be post-processing to manage an independent queue, after a file has been played (i.e. to delete a temporary file that was generated for playback).

I have looked over the output fairly carefully, I think, and have not been able to find any way to relate a message back to where it came from, short of decorating the outbound message to add that in for each instance.  While it is a workable solution, it would be nice if the node, itself, was the definitive authority on identifying which device originated the message.

**Comment by i8beef** [comment]
Its by design that the node doesn't modify the castv2 protocol responses and just hands them through for the payload. That's not to say I couldn't add additional information on non-payload properties on the message though.

Ill consider it as a value add next time I'm making changes.

**Comment by i8beef** [comment]
Added "_castTarget" on output messages in 4.2.2.
