### ISSUE TITLE
Tunein Example 

### ISSUE THREAD

**Issue by Paulf007** [i8beef/node-red-contrib-castv2#84]
Apologies for the stupid question : 
Is it possible to add an example of what the flow would look like to play a Tunein station?
Thank you for the super none!!

Best regards 
Paul

**Comment by i8beef** [comment]
That isnt a supported app. You can control generic media commands once it is running, and if you can find the right APP_ID you could LAUNCH it, but apps tend to use their own custom implementation commands for starting streams, and there's no way for a generic solution to support all of them. This app only supports generic media playing, YouTube, and a few utility things.
