### ISSUE TITLE
Media and TTS in a single cast

### ISSUE THREAD

**Issue by nygma2004** [i8beef/node-red-contrib-castv2#9]
Thanks a lot for this node. I am using this to make my Home Hub say "There is someone at the door" and after show me a still image from my IP camera. Would it be possible to do the two at the same time? So the payload contains a TTS which is being spoken out whilst the media is shown? In my case I am using a still image (jpg), so there is no other audio source.

**Comment by i8beef** [comment]
Not easily... The best I could think of would be using the queue to send a pre generated tts url as one item and then the video stream second, but I'm not sure what the result would be...
