### ISSUE TITLE
Error: Not connected

### ISSUE THREAD

**Issue by guyluz11** [i8beef/node-red-contrib-castv2#90]
Setting my Chromecast IP and default port returns

> Error: Not connected

Same config worked on [node-red-contrib-cast](https://flows.nodered.org/node/node-red-contrib-cast)

**Comment by i8beef** [comment]
Only thing I can think of is you have something in the "Target" field for your connection. That is for mDNS lookup connections, if you're doing direct IP connections it should JUST have IP and PORT specified. 

Other than that, I think you'd have to provide more information, like what you get in an error node or in the console log when it happens.

**Comment by guyluz11** [comment]
My target field was field as you said.

Thank you there is now a connection.
