### ISSUE TITLE
Nest Mini plays audible notification sound when starting DefaultMediaReceiver

### ISSUE THREAD

**Issue by ghost** [i8beef/node-red-contrib-castv2#92]
Hi there, wondering if you might be able to help me out here. I've been using an old Google Mini as our doorbell chime, and it's been working great. However, I recently purchased a new Nest Mini that I'm in the process of setting up. Now, when I cast the doorbell mp3, I first hear a notification sound. I've worked out that this seems to happen when the device is starting the DefaultMediaReceiver app.

The message I send looks like this:
```
{
    "app": "DefaultMediaReceiver",
    "type": "MEDIA",
    "media": {
        "url": "http://.../doorbell.mp3"
    }
}
```

The first time I send this, I hear the notification sound, followed by my doorbell mp3. If I send it again immediately, I only hear the doorbell sound.

If I then send a close message...
```
{
    "app": "DefaultMediaReceiver",
    "type": "CLOSE"
}
```
... followed by the media message above, I once again hear the notification chime. I seems to me like it's notifying me that the DefaultMediaReceiver app was started (or something like that).

I've looked for a setting to disable this, but have had no luck. Any chance you know of a solution?

**Comment by i8beef** [comment]
That isn't exposed by Google as an option unfortunately.

**Comment by ghost** [comment]
Thanks for the quick response @i8beef, looks like I'm mostly out of luck. I did some more searching and found people trying to work around the issue by using volume/mute & delays etc... but it's all pretty clunky. Might just have to put up with it for now. Thanks for the great node btw!
