### ISSUE TITLE
Radio Streaming stopped working

### ISSUE THREAD

**Issue by Toby-Mills** [i8beef/node-red-contrib-castv2#97]
I have been successfully using castv2 for a few years to stream radio to my Chromecast Audio. A few days ago it stopped working, and only reports "**Error: Load failed**" in the log.
I have updated to the latest version of castv2 (4.3.0) but it did not resolve the issue. 
The problem is not with the connection to the Chromecast, as MUTE and VOLUME commands are successfully received.

This is the payload I am sending to the node:

> {
>     "app": "DefaultMediaReceiver",
>     "type": "MEDIA",
>     "media": {
>         "url": "https://21223.live.streamtheworld.com/CAPE_TALK_SC"
>     }
> }

Does anybody have a suggestion for how to troubleshoot the problem?

**Comment by i8beef** [comment]
It looks like the URL you are sending isn't actually loading anything. I'm assuming that something changed on their side and you need to change the URL you're sending.

**Comment by Toby-Mills** [comment]
Thanks a lot for your help, I will try to find an alternative source.
Any chance you have a working example URL I can use to check that my set up is otherwise working?

**Comment by i8beef** [comment]
I don't, but any MP3 should be playable if you can just find one online.
